library(dplyr)
data_path <- "/mnt/hgfs/R_data/tmp/coursera_exploring_data/household_power_consumption.txt"
data <- read.table(data_path, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
plot3_data <- data %>% filter(Date %in% c("1/2/2007","2/2/2007"))
GlobalActivePower <- as.numeric(plot1_data$Global_active_power)
SubMetering1 <- as.numeric(plot3_data$Sub_metering_1)
SubMetering2 <- as.numeric(plot3_data$Sub_metering_2)
SubMetering3 <- as.numeric(plot3_data$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(datetime, SubMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, SubMetering2, type="l", col="red")
lines(datetime, SubMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()